server:
  port: 8010
subscriptionmanager:
  disableHttpOptionsMethod: true
  db:
    host: localhost
    port: 5432
    schema: jas_consent_manager
    user: postgres
    password: password
    poolSize: 5
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest