server:
  port: 8010
subscriptionmanager:
  disableHttpOptionsMethod: true
  cacheMethod: guava
  redis:
    #Will not be used if cacheMethod is guava
    host: localhost
    port: 6379
    password: ${REDIS_PASSWORD:password}
    keep-alive-enabled: ${KEEP_ALIVE_ENABLED:false}
    retry: ${REDIS_RETRY:0}
  subscription:
    defaultPageSize: 20
    maxPageSize: 100
    purposeOfUseDefUrl: classpath:/static/ValueSet/purpose-of-use.json
    hiTypesDefUrl: classpath:/static/ValueSet/health-info-type.json
    subscriptionRequestExpiry: 20000
  db:
    host: localhost
    port: 5432
    schema: data_notification_subscription
    user: postgres
    password: password
    poolSize: 5
  keycloak:
    baseUrl: http://localhost:9001/auth
    clientId: consent-manager
    clientSecret: ${KEYCLOAK_CLIENTSECRET}
    userName: consent-service-admin-user
    password: welcome
    jwkUrl: http://localhost:9001/auth/realms/consent-manager/protocol/openid-connect/certs
    issuer: http://localhost:9001/auth/realms/consent-manager
  gatewayservice:
    baseUrl: http://localhost:8000/v0.5
    requestTimeout: 5000
    enabled: true
    clientId: ncg
    clientSecret: ${GATEWAY_CLIENTSECRET}
    jwkUrl: http://localhost:8000/v0.5/certs
  userservice:
    url: http://localhost:9000
    userIdSuffix: "@ndhm"
  authorization:
    header: Authorization
    idpCertPath: https://healthidbeta.ndhm.gov.in/api/v1/auth/cert
    requireAuthForCerts: true
    idpClientId: ${IDP_CLIENT_ID}
    idpClientSecret: ${IDP_SECRET}
    idpAuthURL: https://dev.ndhm.gov.in/gateway/v0.5/sessions
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  liquibase:
    change-log: classpath:liquibase.xml
    enabled: true